### ISSUE TITLE
Feature request: support sentences

### ISSUE THREAD

**Issue by itsthejoker** [erenbektas/PigLatin#4]
This one will increase the complexity a little bit, but the next step is to allow the user to put in a sentence and have the entire sentence is piggified 😄 

```
Input:
Hello world! This is an example of a longer input.

Output:
Ellohay orldway! Isthay isyay anyay exampleyay ofyay ayay ongerlay inputyay.
```

**Comment by erenbektas** [comment]
Update for this one:

1. No seperate codes for inputs with one word and inputs with more than one word.
2. Output will not come as a list if the input has more than one word.
3. If the first letter of the input is uppercase, first letter of the output will also be uppercase.

What is left:

1. Keeping punctuations at the end of the word.
2. Making the first letter of the words uppercase if it's also like that in the input (for all the words, not only the first one).

**Comment by erenbektas** [comment]
I finally managed to meet all the requirements. Please check them when you have time and some feedback would be awesome!
